apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:

  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;

        keepalive_timeout  65;

        gzip  on;
        gzip_http_version 1.0;
        gzip_comp_level 2;
        gzip_proxied any;
        gzip_vary off;
        gzip_types text/plain text/css application/x-javascript text/xml application/xml application/rss+xml application/atom+xml text/javascript application/javascript application/json text/mathml;
        gzip_min_length  1000;
        gzip_disable     "MSIE [1-6]\.";

        # added the server block
        server {
            listen 80;
            proxy_pass_header Server;
            client_max_body_size 12G;

            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                # app comes from /etc/hosts, Docker added it for us!
                proxy_pass http://app:9090;
            }
        }
    }