version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    working_dir: "/go/src/github.com/kunihiko-t/k8s-example/app"
    command: bash -c "make run"
    environment:
      - GO_ENV=example
    volumes:
      - .:/go/src/github.com/kunihiko-t/k8s-example/app
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_dev:/var/lib/postgresql/data
